services:
  - type: web
    name: orbitrack-cobalt
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: API_PORT
        value: "10000"
      - key: API_CORS_WILDCARD
        value: "1"
      - key: API_URL
        value: https://orbitrack-cobalt.onrender.com
