import type { SynthParams } from './types';

const BASE: SynthParams = {
  masterVolume: 0.75,
  gainAttack: 0.001,
  gainDecay: 0.1,
  gainSustain: 0.7,
  gainRelease: 0.15,
  vcoType: 'sawtooth',
  vcoGain: 1,
  vcoPan: 0,
  vcoDetune: 0,
  vcoOctave: 0,
  sub1Type: 'sawtooth',
  sub1Offset: 0,
  sub1Pan: 0,
  sub1Gain: 0,
  sub2Type: 'sawtooth',
  sub2Offset: 0,
  sub2Pan: 0,
  sub2Gain: 0,
  unisonVoices: 1,
  unisonDetune: 0,
  unisonSpread: 0,
  filterType: 'lowpass',
  filterFreq: 8000,
  filterQ: 0,
  filterAttack: 0,
  filterDecay: 0.1,
  filterEnvAmount: 0,
  lfo1Rate: 4,
  lfo1Depth: 0,
  lfo1Shape: 'sine',
  lfo1Dest: 'none',
  lfo2Rate: 0.5,
  lfo2Depth: 0,
  lfo2Shape: 'sine',
  lfo2Dest: 'none',
  fmEnabled: false,
  fmRatio: 2,
  fmDepth: 0,
  delayTime: 0,
  delayFeedback: 0,
  delayTone: 4400,
  delayAmount: 0,
  reverbType: 'reverb1',
  reverbAmount: 0,
  distortionDist: 0,
  distortionAmount: 0,
  bitCrushDepth: 8,
  bitCrushAmount: 0,
  maxVoices: 8,
  portamentoSpeed: 0,
};

export const SYNTH_PRESETS: Record<string, SynthParams> = {

  // ─── Utility ─────────────────────────────────────────────────────────────

  'INIT': {
    ...BASE,
  },

  // ─── Lead ──────────────────────────────────────────────────────────────

  'Supersaw Lead': {
    ...BASE,
    masterVolume: 0.6,
    vcoType: 'sawtooth',
    unisonVoices: 7,
    unisonDetune: 22,
    unisonSpread: 0.9,
    filterType: 'lowpass',
    filterFreq: 2800,
    filterQ: 1.5,
    filterEnvAmount: 1200,
    filterDecay: 0.35,
    gainAttack: 0.005,
    gainDecay: 0.2,
    gainSustain: 0.8,
    gainRelease: 0.3,
    lfo1Rate: 0.35,
    lfo1Depth: 300,
    lfo1Shape: 'sine',
    lfo1Dest: 'filter',
    reverbType: 'reverb3',
    reverbAmount: 0.2,
  },

  'Trance Lead': {
    ...BASE,
    masterVolume: 0.65,
    vcoType: 'sawtooth',
    sub1Type: 'sawtooth',
    sub1Offset: 0,
    sub1Pan: 0.3,
    sub1Gain: 0.6,
    unisonVoices: 3,
    unisonDetune: 12,
    unisonSpread: 0.7,
    filterType: 'lowpass',
    filterFreq: 600,
    filterQ: 5,
    filterEnvAmount: 5500,
    filterAttack: 0.002,
    filterDecay: 0.15,
    gainAttack: 0.003,
    gainDecay: 0.1,
    gainSustain: 0.8,
    gainRelease: 0.18,
    lfo1Rate: 3.5,
    lfo1Depth: 800,
    lfo1Shape: 'sine',
    lfo1Dest: 'filter',
    reverbType: 'reverb2',
    reverbAmount: 0.15,
  },

  'Rave Lead': {
    ...BASE,
    masterVolume: 0.65,
    vcoType: 'sawtooth',
    vcoGain: 0.9,
    sub1Type: 'square',
    sub1Offset: 0,
    sub1Gain: 0.7,
    unisonVoices: 5,
    unisonDetune: 25,
    unisonSpread: 0.8,
    filterType: 'lowpass',
    filterFreq: 1800,
    filterQ: 3,
    filterEnvAmount: 3500,
    filterDecay: 0.12,
    gainAttack: 0.001,
    gainDecay: 0.08,
    gainSustain: 0.85,
    gainRelease: 0.15,
    distortionDist: 15,
    distortionAmount: 0.25,
    reverbType: 'reverb1',
    reverbAmount: 0.1,
  },

  'Hoover': {
    ...BASE,
    masterVolume: 0.6,
    vcoType: 'sawtooth',
    vcoGain: 0.8,
    sub1Type: 'sawtooth',
    sub1Offset: -12,
    sub1Gain: 0.7,
    sub2Type: 'sawtooth',
    sub2Offset: 7,
    sub2Gain: 0.5,
    unisonVoices: 5,
    unisonDetune: 30,
    unisonSpread: 0.9,
    filterType: 'lowpass',
    filterFreq: 2200,
    filterQ: 2,
    filterEnvAmount: 1500,
    filterDecay: 0.25,
    gainAttack: 0.01,
    gainDecay: 0.3,
    gainSustain: 0.75,
    gainRelease: 0.3,
    portamentoSpeed: 0.06,
    distortionDist: 8,
    distortionAmount: 0.15,
    reverbType: 'reverb2',
    reverbAmount: 0.18,
  },

  'Screamer': {
    ...BASE,
    masterVolume: 0.55,
    vcoType: 'sawtooth',
    unisonVoices: 7,
    unisonDetune: 35,
    unisonSpread: 1,
    filterType: 'lowpass',
    filterFreq: 1200,
    filterQ: 6,
    filterEnvAmount: 6000,
    filterAttack: 0.001,
    filterDecay: 0.2,
    gainAttack: 0.001,
    gainDecay: 0.15,
    gainSustain: 0.9,
    gainRelease: 0.2,
    distortionDist: 20,
    distortionAmount: 0.35,
    reverbType: 'reverb1',
    reverbAmount: 0.12,
  },

  'Mellow Lead': {
    ...BASE,
    masterVolume: 0.7,
    vcoType: 'triangle',
    sub1Type: 'sine',
    sub1Offset: -12,
    sub1Gain: 0.3,
    filterType: 'lowpass',
    filterFreq: 2800,
    filterQ: 0.8,
    gainAttack: 0.01,
    gainDecay: 0.2,
    gainSustain: 0.5,
    gainRelease: 0.3,
    lfo1Rate: 5,
    lfo1Depth: 20,
    lfo1Shape: 'sine',
    lfo1Dest: 'pitch',
    delayTime: 0.18,
    delayFeedback: 0.65,
    delayTone: 4400,
    delayAmount: 0.25,
    reverbType: 'reverb4',
    reverbAmount: 0.18,
  },

  // ─── Acid ──────────────────────────────────────────────────────────────

  'Acid 303': {
    ...BASE,
    masterVolume: 0.75,
    vcoType: 'sawtooth',
    vcoGain: 1,
    filterType: 'lowpass',
    filterFreq: 180,
    filterQ: 12,
    filterEnvAmount: 8000,
    filterAttack: 0.001,
    filterDecay: 0.12,
    gainAttack: 0.001,
    gainDecay: 0.18,
    gainSustain: 0.4,
    gainRelease: 0.08,
    portamentoSpeed: 0.05,
    maxVoices: 1,
    distortionDist: 10,
    distortionAmount: 0.2,
  },

  'Acid Sqr': {
    ...BASE,
    masterVolume: 0.7,
    vcoType: 'square',
    vcoGain: 1,
    filterType: 'lowpass',
    filterFreq: 200,
    filterQ: 14,
    filterEnvAmount: 7500,
    filterAttack: 0.001,
    filterDecay: 0.1,
    gainAttack: 0.001,
    gainDecay: 0.15,
    gainSustain: 0.35,
    gainRelease: 0.06,
    portamentoSpeed: 0.04,
    maxVoices: 1,
    distortionDist: 15,
    distortionAmount: 0.3,
  },

  'Acid Screech': {
    ...BASE,
    masterVolume: 0.6,
    vcoType: 'sawtooth',
    vcoGain: 1,
    filterType: 'lowpass',
    filterFreq: 300,
    filterQ: 18,
    filterEnvAmount: 9000,
    filterAttack: 0.001,
    filterDecay: 0.08,
    gainAttack: 0.001,
    gainDecay: 0.12,
    gainSustain: 0.5,
    gainRelease: 0.05,
    portamentoSpeed: 0.03,
    maxVoices: 1,
    distortionDist: 25,
    distortionAmount: 0.45,
    delayTime: 0.15,
    delayFeedback: 0.5,
    delayTone: 3000,
    delayAmount: 0.12,
  },

  // ─── Bass ──────────────────────────────────────────────────────────────

  'Sub Bass': {
    ...BASE,
    masterVolume: 0.8,
    vcoType: 'sine',
    vcoGain: 1,
    sub1Type: 'sine',
    sub1Offset: -12,
    sub1Gain: 0.8,
    filterType: 'lowpass',
    filterFreq: 250,
    filterQ: 0.5,
    gainAttack: 0.005,
    gainDecay: 0.15,
    gainSustain: 0.9,
    gainRelease: 0.1,
    maxVoices: 1,
  },

  'Phat Pluck': {
    ...BASE,
    masterVolume: 0.75,
    vcoType: 'sawtooth',
    vcoGain: 0.9,
    sub1Type: 'sine',
    sub1Offset: -12,
    sub1Gain: 0.8,
    sub2Type: 'square',
    sub2Offset: 0,
    sub2Gain: 0.4,
    filterType: 'lowpass',
    filterFreq: 300,
    filterQ: 3,
    filterEnvAmount: 6000,
    filterAttack: 0.001,
    filterDecay: 0.1,
    gainAttack: 0.001,
    gainDecay: 0.18,
    gainSustain: 0,
    gainRelease: 0.1,
    distortionDist: 8,
    distortionAmount: 0.15,
  },

  'Reese': {
    ...BASE,
    masterVolume: 0.7,
    vcoType: 'sawtooth',
    vcoGain: 0.8,
    sub1Type: 'sawtooth',
    sub1Offset: 0,
    sub1Pan: 0,
    sub1Gain: 0.8,
    sub2Type: 'sine',
    sub2Offset: -12,
    sub2Gain: 0.6,
    unisonVoices: 2,
    unisonDetune: 8,
    unisonSpread: 0.3,
    filterType: 'lowpass',
    filterFreq: 400,
    filterQ: 2,
    filterEnvAmount: 1500,
    filterDecay: 0.25,
    gainAttack: 0.005,
    gainDecay: 0.3,
    gainSustain: 0.6,
    gainRelease: 0.2,
    lfo1Rate: 0.3,
    lfo1Depth: 300,
    lfo1Shape: 'sine',
    lfo1Dest: 'filter',
    maxVoices: 1,
  },

  'Wobble Bass': {
    ...BASE,
    masterVolume: 0.7,
    vcoType: 'sawtooth',
    vcoGain: 0.9,
    sub1Type: 'sine',
    sub1Offset: -12,
    sub1Gain: 0.7,
    sub2Type: 'square',
    sub2Offset: 0,
    sub2Gain: 0.3,
    filterType: 'lowpass',
    filterFreq: 300,
    filterQ: 4,
    gainAttack: 0.005,
    gainDecay: 0.2,
    gainSustain: 0.8,
    gainRelease: 0.15,
    lfo1Rate: 2,
    lfo1Depth: 3000,
    lfo1Shape: 'sine',
    lfo1Dest: 'filter',
    distortionDist: 12,
    distortionAmount: 0.2,
    maxVoices: 1,
  },

  'FM Bass': {
    ...BASE,
    masterVolume: 0.75,
    vcoType: 'sine',
    vcoGain: 1,
    sub1Type: 'sine',
    sub1Offset: -12,
    sub1Gain: 0.5,
    fmEnabled: true,
    fmRatio: 1.0,
    fmDepth: 400,
    filterType: 'lowpass',
    filterFreq: 800,
    filterQ: 1.5,
    filterEnvAmount: 3500,
    filterAttack: 0.001,
    filterDecay: 0.1,
    gainAttack: 0.001,
    gainDecay: 0.2,
    gainSustain: 0.25,
    gainRelease: 0.12,
    distortionDist: 12,
    distortionAmount: 0.22,
    maxVoices: 1,
  },

  'Deep Bass': {
    ...BASE,
    masterVolume: 0.8,
    vcoType: 'sawtooth',
    vcoGain: 0.7,
    sub1Type: 'sine',
    sub1Offset: -12,
    sub1Gain: 0.9,
    sub2Type: 'sine',
    sub2Offset: -24,
    sub2Gain: 0.5,
    filterType: 'lowpass',
    filterFreq: 200,
    filterQ: 1.5,
    filterEnvAmount: 1800,
    filterAttack: 0.001,
    filterDecay: 0.2,
    gainAttack: 0.005,
    gainDecay: 0.25,
    gainSustain: 0.5,
    gainRelease: 0.15,
    maxVoices: 1,
  },

  // ─── Pluck / Stab ─────────────────────────────────────────────────────

  'Short Pluck': {
    ...BASE,
    masterVolume: 0.7,
    vcoType: 'sawtooth',
    sub1Type: 'sawtooth',
    sub1Offset: -12,
    sub1Gain: 0.5,
    filterType: 'lowpass',
    filterFreq: 350,
    filterQ: 2,
    filterEnvAmount: 6000,
    filterAttack: 0.001,
    filterDecay: 0.08,
    gainAttack: 0.001,
    gainDecay: 0.1,
    gainSustain: 0,
    gainRelease: 0.1,
    reverbType: 'reverb1',
    reverbAmount: 0.12,
  },

  'Stab': {
    ...BASE,
    masterVolume: 0.65,
    vcoType: 'sawtooth',
    vcoGain: 0.85,
    sub1Type: 'sawtooth',
    sub1Offset: 7,
    sub1Pan: 0.3,
    sub1Gain: 0.7,
    sub2Type: 'sawtooth',
    sub2Offset: 3,
    sub2Pan: -0.3,
    sub2Gain: 0.6,
    unisonVoices: 3,
    unisonDetune: 10,
    unisonSpread: 0.6,
    filterType: 'lowpass',
    filterFreq: 800,
    filterQ: 2.5,
    filterEnvAmount: 5000,
    filterAttack: 0.001,
    filterDecay: 0.06,
    gainAttack: 0.001,
    gainDecay: 0.05,
    gainSustain: 0,
    gainRelease: 0.08,
    reverbType: 'reverb2',
    reverbAmount: 0.1,
  },

  'Rave Stab': {
    ...BASE,
    masterVolume: 0.6,
    vcoType: 'sawtooth',
    vcoGain: 0.9,
    sub1Type: 'sawtooth',
    sub1Offset: 7,
    sub1Gain: 0.8,
    sub2Type: 'sawtooth',
    sub2Offset: 12,
    sub2Gain: 0.6,
    unisonVoices: 5,
    unisonDetune: 20,
    unisonSpread: 0.85,
    filterType: 'lowpass',
    filterFreq: 600,
    filterQ: 3,
    filterEnvAmount: 6000,
    filterAttack: 0.001,
    filterDecay: 0.04,
    gainAttack: 0.001,
    gainDecay: 0.04,
    gainSustain: 0,
    gainRelease: 0.06,
    distortionDist: 10,
    distortionAmount: 0.2,
    reverbType: 'reverb1',
    reverbAmount: 0.15,
  },

  'Piano Pluck': {
    ...BASE,
    masterVolume: 0.7,
    vcoType: 'triangle',
    vcoGain: 0.9,
    sub1Type: 'sine',
    sub1Offset: 12,
    sub1Pan: 0.4,
    sub1Gain: 0.3,
    fmEnabled: true,
    fmRatio: 2,
    fmDepth: 60,
    filterType: 'lowpass',
    filterFreq: 1800,
    filterQ: 0.5,
    filterEnvAmount: 2000,
    filterDecay: 0.15,
    gainAttack: 0.001,
    gainDecay: 0.35,
    gainSustain: 0.1,
    gainRelease: 0.3,
    reverbType: 'reverb4',
    reverbAmount: 0.2,
  },

  'Arp Lead': {
    ...BASE,
    masterVolume: 0.6,
    vcoType: 'square',
    vcoGain: 0.85,
    sub1Type: 'square',
    sub1Offset: -12,
    sub1Gain: 0.3,
    filterType: 'lowpass',
    filterFreq: 800,
    filterQ: 1,
    filterEnvAmount: 4000,
    filterAttack: 0.001,
    filterDecay: 0.12,
    gainAttack: 0.001,
    gainDecay: 0.2,
    gainSustain: 0,
    gainRelease: 0.15,
    delayTime: 0.19,
    delayFeedback: 0.65,
    delayTone: 3000,
    delayAmount: 0.2,
    reverbType: 'reverb1',
    reverbAmount: 0.18,
  },

  // ─── Keys ──────────────────────────────────────────────────────────────

  'Hyperpop Keys': {
    ...BASE,
    masterVolume: 0.6,
    vcoType: 'square',
    vcoGain: 0.8,
    sub1Type: 'sawtooth',
    sub1Offset: 12,
    sub1Pan: 0.5,
    sub1Gain: 0.5,
    sub2Type: 'square',
    sub2Offset: 0,
    sub2Pan: -0.5,
    sub2Gain: 0.4,
    unisonVoices: 3,
    unisonDetune: 15,
    unisonSpread: 0.8,
    filterType: 'lowpass',
    filterFreq: 2000,
    filterQ: 2,
    filterEnvAmount: 4000,
    filterDecay: 0.08,
    gainAttack: 0.001,
    gainDecay: 0.15,
    gainSustain: 0.3,
    gainRelease: 0.12,
    bitCrushDepth: 6,
    bitCrushAmount: 0.08,
    delayTime: 0.12,
    delayFeedback: 0.55,
    delayTone: 5000,
    delayAmount: 0.15,
    reverbType: 'reverb3',
    reverbAmount: 0.12,
  },

  'Glitch Keys': {
    ...BASE,
    masterVolume: 0.55,
    vcoType: 'square',
    vcoGain: 0.7,
    sub1Type: 'triangle',
    sub1Offset: 7,
    sub1Pan: 0.6,
    sub1Gain: 0.6,
    sub2Type: 'sawtooth',
    sub2Offset: -5,
    sub2Pan: -0.6,
    sub2Gain: 0.5,
    filterType: 'lowpass',
    filterFreq: 3000,
    filterQ: 1,
    filterEnvAmount: 3000,
    filterDecay: 0.06,
    gainAttack: 0.001,
    gainDecay: 0.12,
    gainSustain: 0.15,
    gainRelease: 0.08,
    bitCrushDepth: 5,
    bitCrushAmount: 0.12,
    distortionDist: 8,
    distortionAmount: 0.15,
    delayTime: 0.08,
    delayFeedback: 0.7,
    delayTone: 6000,
    delayAmount: 0.18,
  },

  'Crystal Keys': {
    ...BASE,
    masterVolume: 0.6,
    vcoType: 'sine',
    vcoGain: 0.9,
    sub1Type: 'triangle',
    sub1Offset: 12,
    sub1Pan: 0.5,
    sub1Gain: 0.4,
    sub2Type: 'sine',
    sub2Offset: 19,
    sub2Pan: -0.5,
    sub2Gain: 0.25,
    fmEnabled: true,
    fmRatio: 3,
    fmDepth: 40,
    filterType: 'lowpass',
    filterFreq: 6000,
    filterQ: 0.3,
    gainAttack: 0.001,
    gainDecay: 0.4,
    gainSustain: 0.15,
    gainRelease: 0.5,
    delayTime: 0.22,
    delayFeedback: 0.6,
    delayTone: 5000,
    delayAmount: 0.2,
    reverbType: 'reverb5',
    reverbAmount: 0.35,
  },

  // ─── Bell / Chime ──────────────────────────────────────────────────────

  'Bell': {
    ...BASE,
    masterVolume: 0.65,
    vcoType: 'sine',
    vcoGain: 1,
    sub1Type: 'sine',
    sub1Offset: 12,
    sub1Pan: 0.4,
    sub1Gain: 0.5,
    sub2Type: 'sine',
    sub2Offset: 19,
    sub2Pan: -0.4,
    sub2Gain: 0.3,
    fmEnabled: true,
    fmRatio: 2.5,
    fmDepth: 200,
    filterType: 'lowpass',
    filterFreq: 5000,
    filterQ: 0.3,
    gainAttack: 0.001,
    gainDecay: 0.6,
    gainSustain: 0.08,
    gainRelease: 0.8,
    reverbType: 'reverb5',
    reverbAmount: 0.5,
    delayTime: 0.28,
    delayFeedback: 0.7,
    delayTone: 3200,
    delayAmount: 0.2,
  },

  'Chime': {
    ...BASE,
    masterVolume: 0.6,
    vcoType: 'sine',
    vcoGain: 0.8,
    sub1Type: 'sine',
    sub1Offset: 4,
    sub1Pan: 0.6,
    sub1Gain: 0.7,
    sub2Type: 'sine',
    sub2Offset: 11,
    sub2Pan: -0.6,
    sub2Gain: 0.7,
    fmEnabled: true,
    fmRatio: 3.5,
    fmDepth: 90,
    filterType: 'lowpass',
    filterFreq: 1400,
    filterQ: 0,
    gainAttack: 0.001,
    gainDecay: 0.5,
    gainSustain: 0,
    gainRelease: 0.3,
    reverbType: 'reverb6',
    reverbAmount: 0.65,
    delayTime: 0.29,
    delayFeedback: 0.72,
    delayTone: 3200,
    delayAmount: 0.2,
    portamentoSpeed: 0.02,
    lfo1Rate: 3.2,
    lfo1Depth: 6,
    lfo1Shape: 'sine',
    lfo1Dest: 'pitch',
  },

  // ─── Pad ───────────────────────────────────────────────────────────────

  'Pad': {
    ...BASE,
    masterVolume: 0.65,
    vcoType: 'sawtooth',
    vcoGain: 0.7,
    sub1Type: 'sawtooth',
    sub1Offset: 0,
    sub1Pan: 0.5,
    sub1Gain: 0.6,
    sub2Type: 'sawtooth',
    sub2Offset: 7,
    sub2Pan: -0.5,
    sub2Gain: 0.5,
    unisonVoices: 5,
    unisonDetune: 12,
    unisonSpread: 0.8,
    filterType: 'lowpass',
    filterFreq: 1000,
    filterQ: 0.5,
    gainAttack: 0.8,
    gainDecay: 0.5,
    gainSustain: 0.7,
    gainRelease: 1.0,
    lfo2Rate: 0.15,
    lfo2Depth: 250,
    lfo2Shape: 'sine',
    lfo2Dest: 'filter',
    reverbType: 'reverb5',
    reverbAmount: 0.55,
    delayTime: 0.38,
    delayFeedback: 0.5,
    delayTone: 5000,
    delayAmount: 0.12,
  },

  'Dark Pad': {
    ...BASE,
    masterVolume: 0.6,
    vcoType: 'sawtooth',
    vcoGain: 0.6,
    sub1Type: 'square',
    sub1Offset: -12,
    sub1Pan: 0.4,
    sub1Gain: 0.7,
    sub2Type: 'triangle',
    sub2Offset: -7,
    sub2Pan: -0.4,
    sub2Gain: 0.5,
    unisonVoices: 3,
    unisonDetune: 8,
    unisonSpread: 0.6,
    filterType: 'lowpass',
    filterFreq: 600,
    filterQ: 1,
    gainAttack: 1.0,
    gainDecay: 0.6,
    gainSustain: 0.6,
    gainRelease: 1.2,
    lfo1Rate: 0.08,
    lfo1Depth: 200,
    lfo1Shape: 'sine',
    lfo1Dest: 'filter',
    reverbType: 'reverb6',
    reverbAmount: 0.7,
  },

  'Drone': {
    ...BASE,
    masterVolume: 0.6,
    vcoType: 'sawtooth',
    vcoGain: 0.7,
    sub1Type: 'sawtooth',
    sub1Offset: 0,
    sub1Pan: 0.45,
    sub1Gain: 0.65,
    sub2Type: 'triangle',
    sub2Offset: -12,
    sub2Pan: -0.45,
    sub2Gain: 0.7,
    unisonVoices: 3,
    unisonDetune: 6,
    unisonSpread: 0.5,
    filterType: 'lowpass',
    filterFreq: 800,
    filterQ: 1.5,
    gainAttack: 0.5,
    gainDecay: 0.6,
    gainSustain: 0.85,
    gainRelease: 1.2,
    lfo1Rate: 0.1,
    lfo1Depth: 400,
    lfo1Shape: 'sine',
    lfo1Dest: 'filter',
    lfo2Rate: 0.06,
    lfo2Depth: 15,
    lfo2Shape: 'sine',
    lfo2Dest: 'pitch',
    reverbType: 'reverb6',
    reverbAmount: 0.75,
  },

  // ─── Percussion ────────────────────────────────────────────────────────

  'HH Synth': {
    ...BASE,
    masterVolume: 0.55,
    vcoType: 'square',
    vcoGain: 0.9,
    sub1Type: 'square',
    sub1Offset: 7,
    sub1Gain: 0.7,
    sub2Type: 'square',
    sub2Offset: 13,
    sub2Gain: 0.5,
    filterType: 'highpass',
    filterFreq: 6000,
    filterQ: 1.5,
    gainAttack: 0.001,
    gainDecay: 0.03,
    gainSustain: 0,
    gainRelease: 0.04,
    distortionDist: 30,
    distortionAmount: 0.4,
    bitCrushDepth: 5,
    bitCrushAmount: 0.15,
  },

  'Kick Synth': {
    ...BASE,
    masterVolume: 0.8,
    vcoType: 'sine',
    vcoGain: 1,
    sub1Type: 'sine',
    sub1Offset: -12,
    sub1Gain: 0.5,
    filterType: 'lowpass',
    filterFreq: 200,
    filterQ: 0,
    filterEnvAmount: 2000,
    filterDecay: 0.04,
    gainAttack: 0.001,
    gainDecay: 0.15,
    gainSustain: 0,
    gainRelease: 0.08,
    fmEnabled: true,
    fmRatio: 1,
    fmDepth: 300,
    maxVoices: 1,
  },

  'Snare Synth': {
    ...BASE,
    masterVolume: 0.7,
    vcoType: 'triangle',
    vcoGain: 0.6,
    sub1Type: 'square',
    sub1Offset: 7,
    sub1Gain: 0.4,
    sub2Type: 'square',
    sub2Offset: 15,
    sub2Gain: 0.3,
    filterType: 'lowpass',
    filterFreq: 4000,
    filterQ: 0,
    filterEnvAmount: 3000,
    filterDecay: 0.06,
    gainAttack: 0.001,
    gainDecay: 0.1,
    gainSustain: 0,
    gainRelease: 0.08,
    distortionDist: 20,
    distortionAmount: 0.3,
    bitCrushDepth: 6,
    bitCrushAmount: 0.08,
  },

  // ─── Character / Misc ─────────────────────────────────────────────────

  'Dist Saw Chord': {
    ...BASE,
    masterVolume: 0.7,
    vcoType: 'sawtooth',
    vcoGain: 0.8,
    sub1Type: 'sawtooth',
    sub1Offset: 3,
    sub1Gain: 0.8,
    sub2Type: 'sawtooth',
    sub2Offset: 10,
    sub2Gain: 0.7,
    unisonVoices: 3,
    unisonDetune: 8,
    unisonSpread: 0.5,
    filterType: 'lowpass',
    filterFreq: 2200,
    filterQ: 0,
    filterAttack: 0.3,
    filterDecay: 0.35,
    filterEnvAmount: 1000,
    gainAttack: 0.35,
    gainDecay: 0.3,
    gainSustain: 0.35,
    gainRelease: 0.35,
    distortionDist: 20,
    distortionAmount: 0.3,
    reverbType: 'reverb4',
    reverbAmount: 0.12,
    lfo1Rate: 6,
    lfo1Depth: 10,
    lfo1Shape: 'sine',
    lfo1Dest: 'pitch',
  },

  'Mellow Chimes': {
    ...BASE,
    masterVolume: 0.7,
    vcoType: 'sine',
    vcoGain: 0.8,
    sub1Type: 'sine',
    sub1Offset: 4,
    sub1Pan: 0.6,
    sub1Gain: 0.75,
    sub2Type: 'sine',
    sub2Offset: 11,
    sub2Pan: -0.6,
    sub2Gain: 0.75,
    filterType: 'lowpass',
    filterFreq: 1400,
    filterQ: 0,
    gainAttack: 0.45,
    gainDecay: 0.4,
    gainSustain: 0,
    gainRelease: 0.2,
    delayTime: 0.28,
    delayFeedback: 0.75,
    delayTone: 3200,
    delayAmount: 0.2,
    reverbType: 'reverb6',
    reverbAmount: 0.7,
    portamentoSpeed: 0.025,
    lfo1Rate: 3.2,
    lfo1Depth: 6,
    lfo1Shape: 'sine',
    lfo1Dest: 'pitch',
  },

  'Bitcrushed': {
    ...BASE,
    masterVolume: 0.6,
    vcoType: 'sawtooth',
    vcoGain: 0.9,
    sub1Type: 'square',
    sub1Offset: 0,
    sub1Gain: 0.5,
    filterType: 'lowpass',
    filterFreq: 3000,
    filterQ: 1,
    filterEnvAmount: 2000,
    filterDecay: 0.15,
    gainAttack: 0.001,
    gainDecay: 0.2,
    gainSustain: 0.4,
    gainRelease: 0.15,
    bitCrushDepth: 4,
    bitCrushAmount: 0.3,
    distortionDist: 10,
    distortionAmount: 0.15,
    delayTime: 0.15,
    delayFeedback: 0.5,
    delayTone: 2500,
    delayAmount: 0.12,
  },
};

/** Maps each factory preset name -> its category folder for the preset browser. */
export const FACTORY_PRESET_FOLDERS: Record<string, string> = {
  'INIT': 'Init',
  // Lead
  'Supersaw Lead': 'Lead',
  'Trance Lead': 'Lead',
  'Rave Lead': 'Lead',
  'Hoover': 'Lead',
  'Screamer': 'Lead',
  'Mellow Lead': 'Lead',
  // Acid
  'Acid 303': 'Acid',
  'Acid Sqr': 'Acid',
  'Acid Screech': 'Acid',
  // Bass
  'Sub Bass': 'Bass',
  'Phat Pluck': 'Bass',
  'Reese': 'Bass',
  'Wobble Bass': 'Bass',
  'FM Bass': 'Bass',
  'Deep Bass': 'Bass',
  // Pluck / Stab
  'Short Pluck': 'Pluck',
  'Stab': 'Pluck',
  'Rave Stab': 'Pluck',
  'Piano Pluck': 'Pluck',
  'Arp Lead': 'Pluck',
  // Keys
  'Hyperpop Keys': 'Keys',
  'Glitch Keys': 'Keys',
  'Crystal Keys': 'Keys',
  // Bell
  'Bell': 'Bell',
  'Chime': 'Bell',
  // Pad
  'Pad': 'Pad',
  'Dark Pad': 'Pad',
  'Drone': 'Pad',
  // Perc
  'HH Synth': 'Perc',
  'Kick Synth': 'Perc',
  'Snare Synth': 'Perc',
  // Character
  'Dist Saw Chord': 'Character',
  'Mellow Chimes': 'Character',
  'Bitcrushed': 'Character',
};
