import type { SynthParams } from './types';

const BASE: SynthParams = {
  masterVolume: 0.75,
  gainAttack: 0.001,
  gainDecay: 0.1,
  gainSustain: 0.7,
  gainRelease: 0.15,
  vcoType: 'sawtooth',
  vcoGain: 1,
  vcoPan: 0,
  vcoDetune: 0,
  sub1Type: 'sawtooth',
  sub1Offset: 0,
  sub1Pan: 0,
  sub1Gain: 0,
  sub2Type: 'sawtooth',
  sub2Offset: 0,
  sub2Pan: 0,
  sub2Gain: 0,
  unisonVoices: 1,
  unisonDetune: 0,
  unisonSpread: 0,
  filterType: 'lowpass',
  filterFreq: 8000,
  filterQ: 0,
  filterAttack: 0,
  filterDecay: 0.1,
  filterEnvAmount: 0,
  lfo1Rate: 4,
  lfo1Depth: 0,
  lfo1Shape: 'sine',
  lfo1Dest: 'none',
  lfo2Rate: 0.5,
  lfo2Depth: 0,
  lfo2Shape: 'sine',
  lfo2Dest: 'none',
  fmEnabled: false,
  fmRatio: 2,
  fmDepth: 0,
  delayTime: 0,
  delayFeedback: 0,
  delayTone: 4400,
  delayAmount: 0,
  reverbType: 'reverb1',
  reverbAmount: 0,
  distortionDist: 0,
  distortionAmount: 0,
  bitCrushDepth: 8,
  bitCrushAmount: 0,
  maxVoices: 8,
  portamentoSpeed: 0,
};

export const SYNTH_PRESETS: Record<string, SynthParams> = {

  // ─── Utility ─────────────────────────────────────────────────────────────

  'INIT': {
    ...BASE,
    masterVolume: 0.75,
    vcoType: 'sawtooth',
    filterFreq: 8000,
  },

  // ─── Lead sounds ─────────────────────────────────────────────────────────

  'Supersaw Lead': {
    ...BASE,
    masterVolume: 0.65,
    vcoType: 'sawtooth',
    unisonVoices: 5,
    unisonDetune: 18,
    unisonSpread: 0.85,
    filterType: 'lowpass',
    filterFreq: 3200,
    filterQ: 1.2,
    filterEnvAmount: 800,
    filterDecay: 0.3,
    lfo1Rate: 0.4,
    lfo1Depth: 280,
    lfo1Shape: 'sine',
    lfo1Dest: 'filter',
    reverbType: 'reverb3',
    reverbAmount: 0.22,
    gainAttack: 0.005,
    gainDecay: 0.15,
    gainSustain: 0.8,
    gainRelease: 0.25,
  },

  'Trance Lead': {
    ...BASE,
    masterVolume: 0.7,
    vcoType: 'sawtooth',
    sub1Type: 'sawtooth',
    sub1Offset: 0,
    sub1Gain: 0.5,
    unisonVoices: 3,
    unisonDetune: 10,
    unisonSpread: 0.6,
    filterType: 'lowpass',
    filterFreq: 800,
    filterQ: 3.5,
    filterEnvAmount: 4500,
    filterAttack: 0.004,
    filterDecay: 0.18,
    lfo1Rate: 3.0,
    lfo1Depth: 600,
    lfo1Shape: 'sine',
    lfo1Dest: 'filter',
    gainAttack: 0.004,
    gainDecay: 0.12,
    gainSustain: 0.75,
    gainRelease: 0.2,
    reverbType: 'reverb2',
    reverbAmount: 0.18,
  },

  'Mellow Lead': {
    ...BASE,
    masterVolume: 0.72,
    vcoType: 'triangle',
    filterType: 'lowpass',
    filterFreq: 3000,
    filterQ: 0.8,
    gainAttack: 0.01,
    gainDecay: 0.2,
    gainSustain: 0.5,
    gainRelease: 0.25,
    lfo1Rate: 4.5,
    lfo1Depth: 22,
    lfo1Shape: 'sine',
    lfo1Dest: 'pitch',
    delayTime: 0.18,
    delayFeedback: 0.68,
    delayTone: 4400,
    delayAmount: 0.28,
    reverbType: 'reverb4',
    reverbAmount: 0.14,
  },

  // ─── Pluck / Stab ─────────────────────────────────────────────────────────

  'Short Pluck': {
    ...BASE,
    masterVolume: 0.7,
    vcoType: 'sawtooth',
    sub1Type: 'sawtooth',
    sub1Offset: -12,
    sub1Gain: 0.45,
    filterType: 'lowpass',
    filterFreq: 400,
    filterQ: 1.8,
    filterEnvAmount: 5500,
    filterAttack: 0.001,
    filterDecay: 0.1,
    gainAttack: 0.001,
    gainDecay: 0.12,
    gainSustain: 0,
    gainRelease: 0.12,
    reverbType: 'reverb1',
    reverbAmount: 0.15,
  },

  'Stab': {
    ...BASE,
    masterVolume: 0.68,
    vcoType: 'sawtooth',
    vcoGain: 0.8,
    sub1Type: 'sawtooth',
    sub1Offset: 7,
    sub1Gain: 0.7,
    sub2Type: 'sawtooth',
    sub2Offset: 3,
    sub2Pan: 0,
    sub2Gain: 0.6,
    filterType: 'lowpass',
    filterFreq: 1600,
    filterQ: 2.0,
    filterEnvAmount: 3200,
    filterAttack: 0.001,
    filterDecay: 0.08,
    gainAttack: 0.001,
    gainDecay: 0.06,
    gainSustain: 0,
    gainRelease: 0.1,
    reverbType: 'reverb2',
    reverbAmount: 0.12,
  },

  'Arp Lead': {
    ...BASE,
    masterVolume: 0.6,
    vcoType: 'square',
    vcoGain: 0.85,
    filterType: 'lowpass',
    filterFreq: 1100,
    filterQ: 0,
    filterEnvAmount: 2500,
    filterAttack: 0.001,
    filterDecay: 0.16,
    gainAttack: 0.001,
    gainDecay: 0.24,
    gainSustain: 0,
    gainRelease: 0.2,
    delayTime: 0.19,
    delayFeedback: 0.67,
    delayTone: 2600,
    delayAmount: 0.17,
    bitCrushDepth: 6,
    bitCrushAmount: 0.05,
    reverbType: 'reverb1',
    reverbAmount: 0.24,
  },

  // ─── Bass ────────────────────────────────────────────────────────────────

  'Bass Deep': {
    ...BASE,
    masterVolume: 0.8,
    vcoType: 'sine',
    vcoGain: 0.9,
    sub1Type: 'sawtooth',
    sub1Offset: -12,
    sub1Gain: 0.6,
    sub2Type: 'sine',
    sub2Offset: -24,
    sub2Gain: 0.45,
    filterType: 'lowpass',
    filterFreq: 180,
    filterQ: 1.5,
    filterEnvAmount: 1200,
    filterAttack: 0.001,
    filterDecay: 0.2,
    gainAttack: 0.005,
    gainDecay: 0.3,
    gainSustain: 0.4,
    gainRelease: 0.2,
  },

  'Acid Bass': {
    ...BASE,
    masterVolume: 0.75,
    vcoType: 'square',
    vcoGain: 0.9,
    sub1Gain: 0,
    filterType: 'lowpass',
    filterFreq: 220,
    filterQ: 8,
    filterEnvAmount: 7000,
    filterAttack: 0.001,
    filterDecay: 0.14,
    gainAttack: 0.001,
    gainDecay: 0.2,
    gainSustain: 0.3,
    gainRelease: 0.12,
    portamentoSpeed: 0.04,
  },

  'FM Bass': {
    ...BASE,
    masterVolume: 0.78,
    vcoType: 'sine',
    vcoGain: 1,
    sub1Gain: 0,
    sub2Gain: 0,
    fmEnabled: true,
    fmRatio: 1.0,
    fmDepth: 320,
    filterType: 'lowpass',
    filterFreq: 1200,
    filterQ: 1.0,
    filterEnvAmount: 2800,
    filterAttack: 0.001,
    filterDecay: 0.12,
    gainAttack: 0.001,
    gainDecay: 0.25,
    gainSustain: 0.2,
    gainRelease: 0.15,
    distortionDist: 12,
    distortionAmount: 0.22,
  },

  // ─── Bell / Chime / Pad ───────────────────────────────────────────────────

  'Bell': {
    ...BASE,
    masterVolume: 0.7,
    vcoType: 'sine',
    vcoGain: 1,
    sub1Type: 'sine',
    sub1Offset: 12,
    sub1Pan: 0.4,
    sub1Gain: 0.55,
    sub2Type: 'sine',
    sub2Offset: 19,
    sub2Pan: -0.4,
    sub2Gain: 0.35,
    fmEnabled: true,
    fmRatio: 2.5,
    fmDepth: 180,
    filterType: 'lowpass',
    filterFreq: 6000,
    filterQ: 0.3,
    gainAttack: 0.001,
    gainDecay: 0.6,
    gainSustain: 0.1,
    gainRelease: 0.8,
    reverbType: 'reverb5',
    reverbAmount: 0.55,
    delayTime: 0.28,
    delayFeedback: 0.76,
    delayTone: 3200,
    delayAmount: 0.22,
  },

  'Chime': {
    ...BASE,
    masterVolume: 0.65,
    vcoType: 'sine',
    vcoGain: 0.8,
    sub1Type: 'sine',
    sub1Offset: 4,
    sub1Pan: 0.6,
    sub1Gain: 0.75,
    sub2Type: 'sine',
    sub2Offset: 11,
    sub2Pan: -0.6,
    sub2Gain: 0.75,
    fmEnabled: true,
    fmRatio: 3.5,
    fmDepth: 80,
    filterType: 'lowpass',
    filterFreq: 1400,
    filterQ: 0,
    gainAttack: 0.001,
    gainDecay: 0.5,
    gainSustain: 0,
    gainRelease: 0.25,
    reverbType: 'reverb6',
    reverbAmount: 0.72,
    delayTime: 0.29,
    delayFeedback: 0.74,
    delayTone: 3200,
    delayAmount: 0.22,
    portamentoSpeed: 0.02,
    lfo1Rate: 3.2,
    lfo1Depth: 6,
    lfo1Shape: 'sine',
    lfo1Dest: 'pitch',
  },

  'Pad': {
    ...BASE,
    masterVolume: 0.7,
    vcoType: 'sawtooth',
    vcoGain: 0.7,
    sub1Type: 'sawtooth',
    sub1Offset: 0,
    sub1Pan: 0.5,
    sub1Gain: 0.6,
    sub2Type: 'sawtooth',
    sub2Offset: 7,
    sub2Pan: -0.5,
    sub2Gain: 0.5,
    unisonVoices: 3,
    unisonDetune: 8,
    unisonSpread: 0.7,
    filterType: 'lowpass',
    filterFreq: 1200,
    filterQ: 0.5,
    gainAttack: 0.85,
    gainDecay: 0.4,
    gainSustain: 0.7,
    gainRelease: 0.9,
    lfo2Rate: 0.18,
    lfo2Depth: 200,
    lfo2Shape: 'sine',
    lfo2Dest: 'filter',
    reverbType: 'reverb5',
    reverbAmount: 0.62,
    delayTime: 0.38,
    delayFeedback: 0.55,
    delayTone: 5000,
    delayAmount: 0.14,
  },

  // ─── Percussion / Noise ───────────────────────────────────────────────────

  'HH Synth': {
    ...BASE,
    masterVolume: 0.55,
    vcoType: 'square',
    vcoGain: 0.9,
    sub1Type: 'square',
    sub1Offset: 7,
    sub1Pan: 0,
    sub1Gain: 0.7,
    sub2Type: 'square',
    sub2Offset: 12,
    sub2Pan: 0,
    sub2Gain: 0.5,
    filterType: 'highpass',
    filterFreq: 6000,
    filterQ: 1.5,
    gainAttack: 0.001,
    gainDecay: 0.03,
    gainSustain: 0,
    gainRelease: 0.05,
    distortionDist: 30,
    distortionAmount: 0.4,
    bitCrushDepth: 5,
    bitCrushAmount: 0.15,
  },

  // ─── Character / Misc ─────────────────────────────────────────────────────

  'Drone': {
    ...BASE,
    masterVolume: 0.65,
    vcoType: 'sawtooth',
    vcoGain: 0.7,
    sub1Type: 'sawtooth',
    sub1Offset: 0,
    sub1Pan: 0.45,
    sub1Gain: 0.6,
    sub2Type: 'triangle',
    sub2Offset: -12,
    sub2Pan: -0.45,
    sub2Gain: 0.7,
    unisonVoices: 3,
    unisonDetune: 6,
    unisonSpread: 0.5,
    filterType: 'lowpass',
    filterFreq: 900,
    filterQ: 1.5,
    gainAttack: 0.5,
    gainDecay: 0.6,
    gainSustain: 0.85,
    gainRelease: 1.2,
    lfo1Rate: 0.12,
    lfo1Depth: 400,
    lfo1Shape: 'sine',
    lfo1Dest: 'filter',
    lfo2Rate: 0.07,
    lfo2Depth: 18,
    lfo2Shape: 'sine',
    lfo2Dest: 'pitch',
    reverbType: 'reverb6',
    reverbAmount: 0.78,
  },

  // ─── Legacy ────────────────────────────────────────────────────────────────

  'Dist Saw Chord': {
    ...BASE,
    masterVolume: 0.8,
    gainAttack: 0.394,
    gainDecay: 0.359,
    gainSustain: 0.3,
    gainRelease: 0.374,
    vcoType: 'sawtooth',
    vcoGain: 0.8,
    sub1Type: 'sawtooth',
    sub1Offset: 3,
    sub1Gain: 0.8,
    sub2Type: 'sawtooth',
    sub2Offset: 10,
    sub2Gain: 0.8,
    filterType: 'lowpass',
    filterFreq: 2400,
    filterQ: 0,
    filterAttack: 0.39,
    filterDecay: 0.39,
    filterEnvAmount: 909,
    reverbType: 'reverb4',
    reverbAmount: 0.125,
    distortionDist: 23.75,
    distortionAmount: 0.326,
    lfo1Rate: 6.06,
    lfo1Depth: 10.6,
    lfo1Shape: 'sine',
    lfo1Dest: 'pitch',
  },

  'Mellow Chimes': {
    ...BASE,
    masterVolume: 0.8,
    gainAttack: 0.485,
    gainDecay: 0.409,
    gainSustain: 0,
    gainRelease: 0.17,
    vcoType: 'sine',
    vcoGain: 0.8,
    sub1Type: 'sine',
    sub1Offset: 4,
    sub1Pan: 0.629,
    sub1Gain: 0.8,
    sub2Type: 'sine',
    sub2Offset: 11,
    sub2Pan: -0.598,
    sub2Gain: 0.8,
    filterType: 'lowpass',
    filterFreq: 1442,
    filterQ: 0,
    delayTime: 0.284,
    delayFeedback: 0.761,
    delayTone: 3192,
    delayAmount: 0.223,
    reverbType: 'reverb6',
    reverbAmount: 0.754,
    portamentoSpeed: 0.025,
    bitCrushDepth: 12,
    bitCrushAmount: 0.034,
    lfo1Rate: 3.22,
    lfo1Depth: 6.06,
    lfo1Shape: 'sine',
    lfo1Dest: 'pitch',
  },
};
